export const fishes = 
{
    "fishes":[
        {
            "userid":1,
			"speciename":"Mackeral",
			"specielocalname":"Katla",
			"specieproportion":90,
			"specieweight":50,
			"dateandtime":"08/21/2022 14:16:30",
			"landingcenterid":"VSPTM",
        },
        {
            "userid":2,
			"speciename":"Pulasa",
			"specielocalname":"Katla",
			"specieproportion":90,
			"specieweight":40,
			"dateandtime":"08/21/2022 13:16:30",
			"landingcenterid":"VSPTM",
        },
        {
            "userid":2,
			"speciename":"Mackeral",
			"specielocalname":"Katla",
			"specieproportion":90,
			"specieweight":70,
			"dateandtime":"08/21/2022 12:16:30",
			"landingcenterid":"VSPTM",
        },
        {
            "userid":3,
			"speciename":"Rohu",
			"specielocalname":"Katla",
			"specieproportion":90,
			"specieweight":80,
			"dateandtime":"08/21/2022 15:16:30",
			"landingcenterid":"VSPTM",
        },
        {
            "userid":1,
			"speciename":"Mackeral",
			"specielocalname":"Katla",
			"specieproportion":90,
			"specieweight":20,
			"dateandtime":"08/21/2022 21:16:30",
			"landingcenterid":"VSPTM",
        },
        {
            "userid":3,
			"speciename":"Pulasa",
			"specielocalname":"Katla",
			"specieproportion":90,
			"specieweight":30,
			"dateandtime":"08/21/2022 19:16:30",
			"landingcenterid":"VSPTM",
        },
        {
            "userid":2,
			"speciename":"Rohu",
			"specielocalname":"Katla",
			"specieproportion":90,
			"specieweight":50,
			"dateandtime":"08/21/2022 23:16:30",
			"landingcenterid":"VSPTM",
        },
        {
            "userid":3,
			"speciename":"Mackeral",
			"specielocalname":"Katla",
			"specieproportion":90,
			"specieweight":40,
			"dateandtime":"08/21/2022 03:16:30",
			"landingcenterid":"VSPTM",
        },
    ]
}